config/routes.rb
MyAppMongoid::Application.routes.draw do 
  devise_for :users ,:path=>"/"
  resources :users do
    resources :blogger_accounts do
      member do
        post 'synchronize'
      end
    end
    resources :wordpress_accounts do
      member do
        post 'synchronize'
      end
    end
    member do
      post 'add_interests'
    end
  end

  resources :articles do
    resources :comments
  end
  root :to => "users#index"

  

end

app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::Timestamps
  require "json"
  field :title, :type => String
  field :content, :type => String

  field :tags , :type => Array ,:default=>[]

  field :liked_by , :type => Array , :default=>[]
  field :disliked_by , :type => Array , :default=>[]
  field :spamed_by , :type => Array , :default=>[]

  field :hidden_tags , :type => Hash , :default=>Hash.new
  field :from , :type => Integer, :default=>0   # 0 for yourfount, 1 for wordpress, 2 for blogger

  has_many :comments , :inverse_of => :article
  belongs_to :owner ,:class_name => "User"

  validates_presence_of :title
  validates_presence_of :content
  validates_presence_of :tags
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


	def edit
		if user_signed_in? && current_user==Article.find(params[:id]).owner
			@article=Article.find(params[:id])
  		elsif user_signed_in? && current_user!=Article.find(params[:id]).owner
  			redirect_to article_path(params[:id]), :notice => "You can edit only your articles!!"
  		else
  			redirect_to new_user_session_path, :notice => "Sign in to edit your article"
  		end
	end

	def update
		if user_signed_in?
			@article=Article.find(params[:id])
			@user=current_user
			engine=Engine.new
			if params[:like]
				@article.liked_by << @user.id
				factor=5
				engine.normalize(@user,@article,factor)
			end
			if params[:unlike]
				@article.liked_by.delete @user.id
				factor=-5
				engine.normalize(@user,@article,factor)
			end
			if params[:dislike]
				@article.disliked_by << @user.id
				factor=-3
				engine.normalize(@user,@article,factor)
			end
			if params[:undislike]
				@article.disliked_by.delete @user.id
				factor=3
				engine.normalize(@user,@article,factor)
			end
			if params[:spam]
				@article.spamed_by << @user.id
			end
			if params[:unspam]
				@article.spamed_by.delete @user.id
			end
			if params[:article]
				params[:article][:tags]=convert_string_to_array_with_downcase(params[:article][:tags])
			end
	  	respond_to do |format|
	  		if @article.update_attributes(params[:article])
	  			format.html {redirect_to @article, :notice => "Article Updated"}
	  		else
	  			format.html {render :action=>"edit", :notice=> "Unable to update Article , sorry! :("}
	  		end
	  	end
	  else
	  	@article=Article.find(params[:id])
	  	respond_to do |format|
	  		format.html { redirect_to new_user_session_path, :notice => "Sign-in to update the article ."}
	  	end
	  end
	end


	def show
		@article=Article.find(params[:id])
		@user=@article.owner
		@profile=@user.profile
		@comments=@article.comments.all
		@comment=@article.comments.build
	end

	def new
		if user_signed_in?
			@article =current_user.articles.build
		else
			redirect_to articles_path, :notice=>"Login to create Article"
		end
	end


	def create
		if user_signed_in?
				params[:article][:tags]=convert_string_to_array_with_downcase(params[:article][:tags])
	      @article= current_user.articles.build(params[:article])
	      respond_to do |format|
	      	if @article.save
	      		format.html {redirect_to @article, :notice => "Article Created"}
	      	else
	      		format.html {render :action=>"new", :notice=> "Unable to create Article , sorry! :("}
	      	end
	      end
	  	end
	end


	def index
		@temp=Article.all
		a=Engine.new
	    @suggested_articles=[]						#to confirm --- suggested_articles is not nil
	    if user_signed_in?
	    	@suggested_articles=a.recommend_articles(current_user,3)
	    end
	end


	def destroy
		@article=Article.find(params[:id])
		respond_to do |format|
			if @article.destroy
				format.html {redirect_to root_path, :notice => "Article Deleted"}
			else
				format.html {render :action=>"show", :notice=> "Unable to delete Article , sorry! :("}
			end
		end
	end

	def convert_string_to_array_with_downcase(string)
		return string.split(",").map{|tag| tag.downcase}
	end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<html>
<div id="ticker">
    </div>
<div class="container2">

<%= form_for(@article) do |f| %>


    <div id="titlefield" > <%= f.text_field :title ,:id=>"title", :style=>"height:40px;width:1000px;text-align:left;font-size:30px",:placeholder =>"Title" %> 
    </div>



<div id="ckeditor" >
    <%= f.text_area :content ,:class=>"ckeditor" %><br/>
</div>

<div id="tags" >
    <h3><font color="white" size="5px" ><%= f.label  "Tags:" %></font></h3>
</div>
   

<link href="tagit-stylish-yellow.css" rel="stylesheet" type="text/css"/>
    <link href="jquery-ui-base-1.8.20.css" rel="stylesheet" type="text/css"/>
    <script src="/js/jquery.1.7.2.min.js"></script>
    <script src="/js/jquery-ui.1.8.20.min.js"></script>
<script src="/js/tagit.js" type="text/javascript" ></script>

    <script>
    $(function() {
            var availableTags = [
                "Fruits",
                "Vegetables",
                "CSS","Python","C","Go Go Go!","Comic"
            ];
                $('#demo1').tagit({tagSource:availableTags,sortable:true});
                $('#demo1GetTags').click(function () {
                showTags($('#demo1').tagit('tags'))
                });
    });
     function showTags(tags) {
                console.log(tags);
                var string = "";
                for (var i in tags)
                    string += tags[i].value + ",";      
        document.getElementById("article_tags").value=string;
                
            }

    </script>
<div id="tagbar" align="center" padding="100px" >
<br /> <br /> <br /> <br />
            <ul id="demo1" name="nameOfSelect" >
                <% if not @article.blank? %>
                    <% @article.tags.each do |tag| %>
                        <li><%= tag %></li>
                    <%end %>
                <% end %>
            </ul>
            <div class="buttons">
                <button id="demo1GetTags" value="Get Tags">Create Article</button>
            </div>


<%= f.hidden_field :tags %><br/><br/>
   
<% end %>
</div>

</html>

app/views/articles/edit.html.erb
<%= render 'form'%>

<%= link_to "Back", :back %>

app/views/articles/index.html.erb
<% for x in @temp %>
<%= link_to x.title,x %>
<br/>

<%end%>


Suggested <br/>

<% for x in @suggested_articles %>
<%= link_to x.title,x %>
<br/>
<%end%>

app/views/articles/new.html.erb
<p style="color:red"><%= notice %></p>
<%= render 'form' %>

app/views/articles/show.html.erb
<div id="box1" >
<div id="showArticle" >
  <div id="title" >
    <h1>  <%= @article.title  %>  </h1>
  </div>
  <div id="articleContent" >
  <p><%= raw @article.content %></p>
  </div>
  <div id="articleDates" >
  <p>Created at: <%=@article.created_at %> || Updated at: <%= @article.updated_at %></p>
  </div>
  <div id="likeDislikeSpam" >
    Likes: <%=@article.liked_by.count %>
    Dislikes: <%= @article.disliked_by.count %>
    Spams: <%=@article.spamed_by.count %>
    <br/>


<% if user_signed_in? %>
  <% if ( @article.liked_by.include? current_user.id ) %>
	<%=form_for(@article,:action=>"update") do |f| %>
	<%= submit_tag "Un-Like", :name=>"unlike"%>
	<% end %>
  <% elsif ( @article.disliked_by.include? current_user.id ) %>
	<%=form_for(@article,:action=>"update") do |f| %>
	<%= submit_tag "Un-Dislike", :name=>"undislike"%>
	<% end %>
  <% elsif ( @article.spamed_by.include? current_user.id ) %>
	<%=form_for(@article,:action=>"update") do |f| %>
	<%= submit_tag "Un-Spam", :name=>"unspam"%>
	<% end %>
  <%  elsif ( not @article.owner.id == current_user.id ) %>
    <%=form_for(@article,:action=>"update") do |f| %>
     <%= submit_tag "Like", :name=>"like"%>
     <%= submit_tag "Dislike",:name=>"dislike"%>
     <%= submit_tag "Spam",:name=>"spam" %>
    <% end %>
  <% end %>
<% else %>
  <%=form_for(@article,:action=>"update") do |f| %>
  <%= submit_tag "Like", :name=>"like"%>
  <%= submit_tag "Dislike",:name=>"dislike"%>
  <%= submit_tag "Spam",:name=>"spam" %>
  <%end%>
<% end %>


<br /> <br />
  </div>
  
  <div id="articleTags" >
  Tags:
  <% @article.tags.each do |sin| %>
  <%= sin %>
  <% end %>
  </div>

  
  
  
<div id="comments" >
  <hr size="5"/>
  
  <h3>Comments:</h3>
  <% sorted_comments = @comments.sort_by { |x| x.created_at } %> 
  <% for comment in sorted_comments %>
  <%= comment.data %><br/> By <%= comment.by.username %><br/>
  Likes:<%= comment.comment_likes.count %> Dislikes:<%= comment.comment_dislikes.count %> Spams:<%= comment.comment_spams.count %>

  <% if user_signed_in? %>
  <% if ( comment.comment_likes.include? current_user.email ) %>
  <%=form_for [@article,comment] do |f| %>
  <%= f.hidden_field :comment_id, { :value => comment.id } %> 
  <%= submit_tag "Un-Like", :name=>"unlike"%>
  <% end %>
  <% elsif ( comment.comment_dislikes.include? current_user.email ) %>
  <%=form_for [@article,comment] do |f| %>
  <%= submit_tag "Un-Dislike", :name=>"undislike"%>
  <%= f.hidden_field :comment_id, { :value => comment.id } %>
  <% end %>
  <% elsif ( comment.comment_spams.include? current_user.email ) %>
  <%=form_for [@article,comment] do |f| %>
  <%= submit_tag "Un-Spam", :name=>"unspam"%>
  <%= f.hidden_field :comment_id, { :value => comment.id } %> 
  <% end %>
  <% elsif ( not comment.by.email == current_user.email ) %>
  <%=form_for [@article,comment] do |f| %>
  <%= f.hidden_field :comment_id, { :value => comment.id } %>
  <%= submit_tag "Like", :name=>"like"%>
  <%= submit_tag "Dislike",:name=>"dislike"%>
  <%= submit_tag "Spam",:name=>"spam" %>
  <%end%>
  <% else %>
  <%= link_to "Delete",[@article,comment],:confirm=>"Are you sure?", :method=>:delete ,:id=>comment.id %>
  <% end %>
  <% else %>
  <%=form_for [@article,comment] do |f| %>
  <%= f.hidden_field :comment_id, { :value => comment.id } %>
  <%= submit_tag "Like", :name=>"like"%>
  <%= submit_tag "Dislike",:name=>"dislike"%>
  <%= submit_tag "Spam",:name=>"spam" %>
  <%end%>
  <% end %>
  </div>

  <div id="commentform" >
  <hr/>
  <%end %>
  <%= render :template=>"comments/_form"%>
  <hr size="5"/>
  <% if user_signed_in? && current_user==Article.find(params[:id]).owner%>
  </div>
  <div id="buttons" >
  <%= link_to "Edit", edit_article_path(params[:id]) %> <%= link_to "Delete",@article,:confirm=>"Are you sure??", :method=> :delete%><br/><br/>
  <% end %>
  <%= link_to "Home", root_path %> <%= link_to "Back", :back%>
  </div>
  

</div>
<div id="about_box" >

<div id="about_in_show" >
<%= render "/users/about" %>
</div>
</div>


</div>