config/routes.rb
MyAppMongoid::Application.routes.draw do 
  devise_for :users ,:path=>"/"
  resources :users do
    resources :blogger_accounts do
      member do
        post 'synchronize'
      end
    end
    resources :wordpress_accounts do
      member do
        post 'synchronize'
      end
    end
    member do
      post 'add_interests'
    end
  end

  resources :articles do
    resources :comments
  end
  root :to => "users#index"

  

end

app/models/user.rb
class User
  include Mongoid::Document

  after_create :init_func

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,:confirmable,
         :recoverable, :rememberable, :trackable, :validatable  ,:authentication_keys => [:login]


## Database authenticatable
  field :email,              :type => String, :null => false
  field :encrypted_password, :type => String, :null => false

## Confirmable
   field :confirmation_token,   :type => String
   field :confirmed_at,         :type => Time
   field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable
  
## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

## Rememberable
  field :remember_created_at, :type => Time

## Trackable
  field :sign_in_count,      :type => Integer
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String


#User Field
  field :username ,          :type => String
  field :email,              :type => String

  has_many :comments , :inverse_of => :by
  has_many :articles, :inverse_of => :owner
  has_one :profile, :inverse_of=>:user
  has_one :blogger_account , :inverse_of=>:user
  has_one :wordpress_account , :inverse_of=>:user



  attr_accessor :login
  accepts_nested_attributes_for :profile

  validates :email, :confirmation => true
  validates_uniqueness_of :username 

  def self.find_for_database_authentication(conditions)
    login = conditions.delete(:login)
    self.any_of({ :username => login }, { :email => login }).first
  end

  def init_func
  	if self.profile.nil?
  	 self.profile=self.build_profile
  	end
  	
  	self.profile.save
  	self.save
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if user_signed_in?
      @my_articles=current_user.articles.all
      @all_articles=Article.all
      @user=current_user
      @profile=@user.profile
      @blogger_account=@user.blogger_account
      @wordpress_account=@user.wordpress_account
      a=Engine.new
      @suggested_articles=[]						#to confirm --- suggested_articles is not nil 
      @suggested_articles=a.recommend_articles(current_user,50)
      if params[:skip]
        session[:skip]=1
      end
    end
  end
  def show
    @user=User.find(params[:id])
    @profile=@user.profile
  end

  def new
    @user=current_user
  end
  
  def update
    params[:user][:profile][:interests]= params[:user][:profile][:interests].delete(' ')
    params[:user][:profile][:interests]= params[:user][:profile][:interests].split(',')
    params[:user][:profile][:interests]= params[:user][:profile][:interests].uniq 			#this all is changing tags , string to array
=begin This parameters have to be added later
    params[:user][:profile][:employer]= params[:user][:profile][:employer].delete(' ')
    params[:user][:profile][:employer]= params[:user][:profile][:employer].split(',')
    params[:user][:profile][:employer]= params[:user][:profile][:employer].uniq 

    params[:user][:profile][:school]= params[:user][:profile][:school].delete(' ')
    params[:user][:profile][:school]= params[:user][:profile][:school].split(',')
    params[:user][:profile][:school]= params[:user][:profile][:school].uniq 

    params[:user][:profile][:undergrad_university]= params[:user][:profile][:undergrad_university].delete(' ')
    params[:user][:profile][:undergrad_university]= params[:user][:profile][:undergrad_university].split(',')
    params[:user][:profile][:undergrad_university]= params[:user][:profile][:undergrad_university].uniq     

    params[:user][:profile][:postgrad_university]= params[:user][:profile][:postgrad_university].delete(' ')
    params[:user][:profile][:postgrad_university]= params[:user][:profile][:postgrad_university].split(',')
    params[:user][:profile][:postgrad_university]= params[:user][:profile][:postgrad_university].uniq  
    session[:skip]=1
=end

    @user=current_user
    respond_to do |format|                                                                                                         #check if profile already exists
      @profile= @user.profile
      if @profile.update_attributes(params[:user][:profile])                                             #update attributes
        session[:skip]=1
        format.html {redirect_to root_path, :notice => "Profile Updated"}
      else
        format.html {render :action=>"edit", :notice=> "Unable to update profile , sorry! :("}
      end
    end
  end

  def edit
    if user_signed_in? && current_user==User.find(params[:id])
      @user=current_user
      @profile=@user.profile
      @profile.interests=@profile.interests.join(',').to_a                             #convert interests (array) into string
      @profile.employer=@profile.employer.join(',').to_a
      @profile.school=@profile.school.join(',').to_a
      @profile.undergrad_university=@profile.undergrad_university.join(',').to_a
      @profile.postgrad_university=@profile.postgrad_university.join(',').to_a
    elsif user_signed_in? && current_user!=User.find(params[:id])
      redirect_to user_path(params[:id]), :notice => "You can't edit other user's profile"
    else 
      redirect_to new_user_session_path, :notice => "Sign in to edit your profile"
    end
  end

  def top_articles(user, number)
    @top=Article.any_in(:tags  => user.profile.interests)
     if @top.length<=number.to_i
       return @top
     else
       @top=@top.order_by([:title, :asc])
       return @top
     end
  end

  def add_interests
    if user_signed_in?
      @user=User.find(params[:id])
      @profile=@user.profile
      interests=params[:interests]
      interests=interests.split(",")
      @profile.interests=@profile.interests+interests
      if @profile.save
        redirect_to root_path , :notice => "You seem like a interesting person! ;)"
      else
        redirect_to root_path , :notice => "Ops! Can't save your interests, please try again or report us."
      end  
    end    
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_homepage_with_login.html.erb
<% if  @profile.interests.count < 2 %>
  <%= render "interest_grid"  %>
<% elsif @user.sign_in_count==1 && session[:skip].nil? %>
    <%=render "form" %>
    <%= link_to "Skip",{:action=>"index",:controller=>"users",:skip=>1},:method=>:get %>
<% else %>
  <div id="blogger_and_wordpress" >
  <% if @blogger_account.nil? %>
     <%=  link_to image_tag("blogger_unsynced.png" ,:id=>"blogger_unsync"), new_user_blogger_account_path(@user) %> <br/> 
  <% else %>
    <%= link_to image_tag("blogger_synced.png" ,:id=>"blogger_sync" ),
    user_blogger_account_path(@user,@blogger_account) %><br/>
  <%end %>

  <% if @wordpress_account.nil? %>
    <%=  link_to image_tag("wordpress_unsynced.png" ,:id=>"wordpress_unsync" ),new_user_wordpress_account_path(@user) %> <br/>  
  <% else %>
    <%= link_to image_tag("wordpress_synced.png" ,:id=>"wordpress_sync" ),user_wordpress_account_path(@user,@wordpress_account) %><br/>
  <%end %>
  </div>
  <%= render "box"%>
  <%= render "about"%>
<% end %>

app/views/users/_homepage_without_login.html.erb
<!--  Here all the code of without login home page should come, the code for interest grid and recommended articles without login-in is to added later. -->
<%= render :file => 'devise/registrations/new' %>

app/views/users/_mydiv.html.erb
<html>
<div id="mydiv">
		<div onClick="addpicture()" style="font:20px bold; cursor:hand">Click here for picture</div>
		<div onClick="addarticle()" style="font:20px bold; cursor:hand">Click here for article</div>

</div>

</html>

app/views/users/_pnotif.html.erb
<html>
<div id="pnotif">
<h2 style="background-color:#0099FF;color:#FFFFFF;width:100%">Personal Notifications</h2>
 <DIV id="innerpnotif" >
Personal Notifications	
</DIV><!-- inner pnotif-->

</div> 
</html>

app/views/users/_register.html.erb
<h2>Sign up</h2>

<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>
<table>
    <tr>
      <td>
      <%= f.label :email %><br />
      </td>
      <td>
      <%= f.email_field :email %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label :username %><br />
      </td>
      <td>
        <%= f.text_field :username %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label :password %><br />
      </td>
      <td>
        <%= f.password_field :password %>
      </td>
      </tr>
      <td>
        <%= f.label :password_confirmation %><br />
        </td>
        <td>
        <%= f.password_field :password_confirmation %>
        </td>
      </tr>
</table>
  <div><%= f.submit "Sign up" %></div>
<% end %>

<%= render :partial => "devise/shared/links" %>
<%= link_to "Home", root_path %>

app/views/users/_right.html.erb
<html>
<div id="righttot" >
				   
			<input  value="Search"/>   <input type="submit" style=";background-color:#0099FF;border:0px;height:25" value="GO"/>

			   <br/>
			   <br/>
			   <br/>
	   		   <TABLE cellspacing=0 cellpadding=2 id=header bgcolor=#0099FF style="float:center" width="200px">
			   <COL WIDTH=100% >
			   <tr height=15%>
			   <th width=100%  style="font-family:arial;text-align:center" ><font color="white">Friends art</font></th></tr>
			   <tr height=15%>

			   <th width=100%  style="font-family:arial;text-align:center;" ><font color="white">Friends activity</font></th></tr>
			   <tr height=15%>

			   <th width=100% style="font-family:arial;text-align:center;"><font color="white">Artist suggestions</font></th></tr>
			   <tr height=15%>

			   <th width=100% style="font-family:arial;text-align:center;"><font color="white">Art suggestions</font></th></tr>

			   </TABLE>
			   <br/>
			   <br/>
			   <br/>


                             
</div>
</html>

app/views/users/_ticker.html.erb
<html>
<div id="tickr">
Suggestion ticker: (like the Mtv ticker it will show artist/art suggestions and friends art and activity)
</div>
</html>

app/views/users/_top.html.erb
<html>
<div class="container">
<div id="ticker">
<div id="topmost" >
		<TABLE  cellspacing=0  cellpadding=2 id=header  >

			     <COL WIDTH=1000><COL WIDTH=500><COL WIDTH=200><COL WIDTH=300>
			   <tr height=30>
		           <th width=30%  style="text-align:left" ><h1 id="logo" style="cursor:pointer">YourFount</h1></th>
	  	           <th width=20%  style="text-align:left;" ><h1><%= current_user.username %></h1></th>
		           <th id="callprofile" width=25% style="text-align:center;"><font color="white">
		           	<h1 id="create_new_article"><%= link_to "Create new article", new_article_path %></h1>
		           </font></th>
			   <th width=70 style="text-align:right;" ><div id="highlightthis"><ul><li id="topright" style="text-align:center;"><img id="imagezoom" height=30 width=40% src="/assets/down_arrow2.jpeg" >

									<ul class="options">
										<li class="options1" ><%= link_to "Settings", edit_user_path(current_user.id), {:class=>"topright1" }%></li>
										<li class="options1" ><%= link_to "Sign Out",destroy_user_session_path , :method=>:delete, :class=>'topright1'%></li>
									</ul></ul>
			   </th>
			   </tr>
			   </TABLE>

</div> <!--topmost-->
</div>

</div>
</html>

app/views/users/_top2.html.erb
<html>
<div id="tickr">
<div id="topmost" >
		<TABLE  cellspacing=0 border=0 cellpadding=2 id=header >
			
			     <COL WIDTH=1000><COL WIDTH=500><COL WIDTH=200><COL WIDTH=300>
			   <tr height=30>
		           <th width=80%  style="text-align:left" ><h1>YourFount</h1></th>
	  	           <th width=20%  style="text-align:left;" ><h2><%= link_to "Register" ,new_user_registration_path , :style => 'text-decoration: none' %> | <%= link_to "Log in" , new_user_session_path , :style => 'text-decoration: none'%></h2></th>
			   </tr>
			   </TABLE>
		<p  id="profile"></p>
</div> <!--topmost-->
</div>
</html>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<% if user_signed_in? &&  current_user==@user %>
	<div id="homepage_with_login">
			<%= render "homepage_with_login" %>
	</div>
<% else %>
	<div id="homepage_without_login">
			<%= render "homepage_without_login" %>
	</div>
<%end%>

app/views/users/index.js.erb
<% if user_signed_in? &&  current_user==@user %>
	$("#homepage_with_login").empty().append("<%= j( render :partial=>'homepage_with_login') %>")
<% else %>
	$("#homepage_without_login").empty().append("<%= j( render :partial=>'homepage_without_login') %>")
<% end %>

app/views/users/show.html.erb
<% if user_signed_in? && @user==current_user %>
	Your Personal Blog. ( Coming Soon ;) )
<% else %>
	<%= render "about" %>
<%end%>